GRAPHQL http://localhost:3000/graphql

query  Coffees {
  coffees {
    id
    name
    flavors {
       name
    }
  }
}

###
GRAPHQL http://localhost:3000/graphql

query  GetCoffee($coffeeID: ID!) {
  coffee(id: $coffeeID) {
    id
    name
    flavors {
        name
    }
  }
}

{
  "coffeeID": 10
}

###
GRAPHQL http://localhost:3000/graphql

mutation CreateCoffee {
  createCoffee(input: {
    name: "Shipwreck Roast",
    brand: "Buddybrew",
    flavors: ["chocolate", "vanilla"]
  }) {
    id,
    name,
    brand,
    flavors {
        name
    }
  }
}

###
GRAPHQL http://localhost:3000/graphql

mutation deleteCoffee($coffeeID: ID!) {
  deleteCoffee(id: $coffeeID) {
      name
  }
}

{
  "coffeeID": 4
}
