GRAPHQL http://localhost:3000/graphql

query  Coffees {
  coffees {
    id
    name
  }
}

###
GRAPHQL http://localhost:3000/graphql

query  GetCoffee($coffeeID: ID!) {
  coffee(id: $coffeeID) {
    id
    name
  }
}

{
  "coffeeID": "1"
}

###
GRAPHQL http://localhost:3000/graphql

mutation CreateCoffee {
  createCoffee(input: {
    name: "test",
    brand: "test",
    flavors: ["test"]
  }) {
    id
    name
  }
}
